name: project
options:
  bundleIdPrefix: io.briskml
  deploymentTarget:
    macOS: '10.10'
  usesTabs: false
  indentWidth: 2
  createIntermediateGroups: true
settings:
  CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: true
  CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: true
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: false
  STRIP_SWIFT_SYMBOLS: false
targets:
  HackerNews:
    type: application
    platform: macOS
    sources:
      - Resources
      - Sources
    settings:
      HEADER_SEARCH_PATHS: '$(STDLIB_PATH) $(HEADER_SEARCH_PATHS)'
      LIBRARY_SEARCH_PATHS: '$(STDLIB_PATH)'
      OTHER_LDFLAGS: '-framework Cocoa'
    configFiles:
      Debug: env.xcconfig
      Release: env.xcconfig
    dependencies:
      - framework: $(BUILD_PATH)/bin/app.exe.o
        embed: false
    info:
      path: Info.plist
      properties:
        LSMinimumSystemVersion: '$(MACOSX_DEPLOYMENT_TARGET)'
        LSApplicationCategoryType: public.app-category.developer-tools
        NSHighResolutionCapable: true
        NSRequiresAquaSystemAppearance: true
        NSHumanReadableCopyright: 'Copyright © 2019 Brisk Contributors. All rights reserved.'
