variables:
  ESY__PREFIX: $(build.binariesDirectory)/.esy
  NPM_CONFIG_PREFIX: $(agent.homeDirectory)/.npm
jobs:
  - job: MacOS
    pool:
      vmImage: "macOS 10.13"
    steps:
      - script: |
          echo '##vso[task.prependpath]$(NPM_CONFIG_PREFIX)/bin'
        displayName: "Setup env"
      - script: npm -g install esy@next
        displayName: "Install esy"
      - script: |
          esy install
        displayName: "Install dependencies"
      - script: |
          esy build:core
          esy test:core
        displayName: "Build and test core"
      - script: |
          esy build:mac
          esy test:mac
        displayName: "Build and test renderer-macos"
      - script: |
          esy bootstrap:mac
          esy build:tester_mac
        displayName: "Build and test tester-macos"
  - job: Linux
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - script: |
          echo '##vso[task.prependpath]$(NPM_CONFIG_PREFIX)/bin'
        displayName: "Setup env"
      - script: npm -g install esy@next
        displayName: "Install esy"
      - script: |
          esy install
        displayName: "Install dependencies"
      - script: |
          esy build:core
          esy test:core
        displayName: "Build and test core"
